package nudge;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import nudge.exception.NudgeException;
import nudge.parser.CommandType;
import nudge.parser.Parser;
import nudge.storage.Storage;
import nudge.task.Task;
import nudge.task.TaskList;
import nudge.ui.Ui;

/**
 * Executes commands for the Nudge chatbot application.
 */
public class Nudge {
    private static final String EXIT_MESSAGE =
            "Okay, I'll leave you to it. I'll be here if you need another nudge!";
    private static final String WELCOME_MESSAGE = "Hey! I'm Nudge. How can I help you today?";

    private final String startupWarning;
    private final Ui ui;
    private TaskList tasks;

    /**
     * Creates a Nudge chatbot and loads its saved tasks.
     */
    public Nudge() {
        ui = new Ui();

        String loadWarning = null;
        try {
            tasks = new TaskList(Storage.load());
        } catch (IOException | NudgeException exception) {
            tasks = new TaskList();
            loadWarning = "I couldn't load your saved task list.";
        }
        startupWarning = loadWarning;
    }

    /**
     * Runs the console version of Nudge.
     *
     * @param args command-line arguments.
     */
    public static void main(String[] args) {
        new Nudge().run();
    }

    /**
     * Runs the command loop until the user exits or the input stream ends.
     */
    public void run() {
        ui.showWelcome();
        if (startupWarning != null) {
            ui.showResponse(NudgeResponse.message(startupWarning));
        }

        boolean shouldExit = false;
        while (!shouldExit && ui.hasNextCommand()) {
            NudgeResponse response = getResponse(ui.readCommand());
            ui.showResponse(response);
            shouldExit = response.shouldExit();
        }

        if (!shouldExit) {
            ui.showResponse(NudgeResponse.exitMessage(EXIT_MESSAGE));
        }
    }

    /**
     * Returns the greeting and any warning produced while loading saved tasks.
     *
     * @return startup text for the graphical interface.
     */
    public String getStartupMessage() {
        if (startupWarning == null) {
            return WELCOME_MESSAGE;
        }
        return WELCOME_MESSAGE + System.lineSeparator() + System.lineSeparator() + startupWarning;
    }

    /**
     * Executes one user command and returns the response to display.
     *
     * @param command command entered by the user.
     * @return response generated by Nudge.
     */
    public NudgeResponse getResponse(String command) {
        try {
            CommandType commandType = Parser.parseCommandType(command);
            return switch (commandType) {
                case BYE -> NudgeResponse.exitMessage(EXIT_MESSAGE);
                case LIST -> getTaskListResponse(tasks.getTasks(),
                        "Here are the tasks in your list:");
                case FIND -> getTaskListResponse(tasks.find(Parser.parseFindKeyword(command)),
                        "Here are the matching tasks in your list:");
                case SORT -> {
                    Parser.validateSortCommand(command);
                    yield sortTasks();
                }
                case MARK -> markTask(Parser.parseTaskIndex(command, "mark"));
                case UNMARK -> unmarkTask(Parser.parseTaskIndex(command, "unmark"));
                case DELETE -> deleteTask(Parser.parseTaskIndex(command, "delete"));
                case TODO -> addTask(Parser.parseTodo(command));
                case DEADLINE -> addTask(Parser.parseDeadline(command));
                case EVENT -> addTask(Parser.parseEvent(command));
                case UNKNOWN -> throw new NudgeException("I don't recognize that command. "
                        + "Try: todo, deadline, event, list, find, sort, mark, unmark, delete, "
                        + "or bye.");
            };
        } catch (NudgeException exception) {
            return NudgeResponse.error(exception.getMessage());
        }
    }

    /**
     * Adds a task and returns confirmation with the updated task count.
     *
     * @param task task to add.
     * @return confirmation of the added task.
     * @throws NudgeException if the task list cannot be written to disk.
     */
    private NudgeResponse addTask(Task task) throws NudgeException {
        tasks.add(task);
        try {
            saveTasks();
        } catch (NudgeException exception) {
            tasks.delete(tasks.getSize() - 1);
            throw exception;
        }

        String taskLabel = tasks.getSize() == 1 ? "task" : "tasks";
        return NudgeResponse.withDetails("Nudge received! I've added:",
                List.of(task.toString()),
                "You now have " + tasks.getSize() + " " + taskLabel + " on your radar.");
    }

    /**
     * Marks a task as done, reverting the change if it cannot be saved.
     *
     * @param taskIndex zero-based index of the task to mark.
     * @return confirmation of the marked task.
     * @throws NudgeException if the index is invalid or the task list cannot be saved.
     */
    private NudgeResponse markTask(int taskIndex) throws NudgeException {
        updateTaskStatus(taskIndex, true);
        return NudgeResponse.withDetails("Nice! I've marked this task as done:",
                tasks.get(taskIndex).toString());
    }

    /**
     * Marks a task as not done, reverting the change if it cannot be saved.
     *
     * @param taskIndex zero-based index of the task to unmark.
     * @return confirmation of the unmarked task.
     * @throws NudgeException if the index is invalid or the task list cannot be saved.
     */
    private NudgeResponse unmarkTask(int taskIndex) throws NudgeException {
        updateTaskStatus(taskIndex, false);
        return NudgeResponse.withDetails("OK, I've marked this task as not done yet:",
                tasks.get(taskIndex).toString());
    }

    /**
     * Updates a task's status, restoring its original status if saving fails.
     *
     * @param taskIndex zero-based index of the task to update.
     * @param shouldMark true to mark the task, or false to unmark it.
     * @throws NudgeException if the index is invalid or the task list cannot be saved.
     */
    private void updateTaskStatus(int taskIndex, boolean shouldMark) throws NudgeException {
        Task task = tasks.get(taskIndex);
        boolean wasDone = task.isDone();
        if (shouldMark) {
            tasks.mark(taskIndex);
        } else {
            tasks.unmark(taskIndex);
        }
        try {
            saveTasks();
        } catch (NudgeException exception) {
            if (wasDone) {
                tasks.mark(taskIndex);
            } else {
                tasks.unmark(taskIndex);
            }
            throw exception;
        }
    }

    /**
     * Deletes a task, restoring it if the updated list cannot be saved.
     *
     * @param taskIndex zero-based index of the task to delete.
     * @return confirmation of the deleted task.
     * @throws NudgeException if the index is invalid or the task list cannot be saved.
     */
    private NudgeResponse deleteTask(int taskIndex) throws NudgeException {
        Task deletedTask = tasks.delete(taskIndex);
        try {
            saveTasks();
        } catch (NudgeException exception) {
            tasks.add(taskIndex, deletedTask);
            throw exception;
        }

        String taskLabel = tasks.getSize() == 1 ? "task" : "tasks";
        return NudgeResponse.withDetails("Noted. I've removed this task:",
                List.of(deletedTask.toString()),
                "You now have " + tasks.getSize() + " " + taskLabel + " on your radar.");
    }

    /**
     * Sorts deadlines by date and saves the new task order, restoring the old order if saving
     * fails.
     *
     * @return the complete task list in its resulting order.
     * @throws NudgeException if the task list cannot be saved.
     */
    private NudgeResponse sortTasks() throws NudgeException {
        List<Task> originalOrder = new ArrayList<>(tasks.getTasks());
        tasks.sortDeadlinesByDate();
        try {
            saveTasks();
        } catch (NudgeException exception) {
            tasks = new TaskList(originalOrder);
            throw exception;
        }
        return getTaskListResponse(tasks.getTasks(),
                "Here are your tasks, with deadlines sorted by date:");
    }

    /**
     * Creates a numbered response for a collection of tasks.
     *
     * @param matchingTasks tasks to include in the response.
     * @param message response shown above the tasks.
     * @return response containing the numbered tasks.
     */
    private NudgeResponse getTaskListResponse(List<Task> matchingTasks, String message) {
        ArrayList<String> taskDetails = new ArrayList<>();
        for (int i = 0; i < matchingTasks.size(); i++) {
            taskDetails.add((i + 1) + "." + matchingTasks.get(i));
        }
        return NudgeResponse.withDetails(message, taskDetails);
    }

    /**
     * Saves the current task list and reports an error when it cannot be saved.
     *
     * @throws NudgeException if the task list cannot be written to disk.
     */
    private void saveTasks() throws NudgeException {
        try {
            Storage.save(tasks.getTasks());
        } catch (IOException exception) {
            throw new NudgeException("I couldn't save your task list.");
        }
    }
}
