package nudge.gui;

import java.io.IOException;
import java.net.URL;
import java.util.Collections;

import javafx.beans.binding.Bindings;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;

/**
 * Represents one chat message with a text bubble and a speaker avatar.
 */
public class DialogBox extends HBox {
    private static final double NUDGE_AVATAR_SIZE = 36;
    private static final double USER_AVATAR_SIZE = 28;
    private static final double NUDGE_BUBBLE_SIDE_SPACE = 64;
    private static final double USER_BUBBLE_MAX_WIDTH = 300;
    private static final Image NUDGE_AVATAR = loadImage("/images/nudge-profile.png");
    private static final Image USER_AVATAR = loadImage("/images/user-profile.png");

    @FXML
    private Label dialog;
    @FXML
    private ImageView avatar;

    private DialogBox(String text) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(
                    DialogBox.class.getResource("/view/DialogBox.fxml"));
            fxmlLoader.setController(this);
            fxmlLoader.setRoot(this);
            fxmlLoader.load();
        } catch (IOException exception) {
            throw new IllegalStateException("Unable to load a dialog box.", exception);
        }

        dialog.setText(text);
    }

    /**
     * Creates a dialog aligned to the right for a command entered by the user.
     *
     * @param text command entered by the user.
     * @return user dialog box.
     */
    public static DialogBox getUserDialog(String text) {
        DialogBox dialogBox = new DialogBox(text);
        dialogBox.avatar.setImage(USER_AVATAR);
        dialogBox.avatar.setAccessibleText("You");
        dialogBox.setAvatarSize(USER_AVATAR_SIZE);
        dialogBox.dialog.setMaxWidth(USER_BUBBLE_MAX_WIDTH);
        return dialogBox;
    }

    /**
     * Creates a dialog aligned to the left for a response from Nudge.
     *
     * @param text response generated by Nudge.
     * @return Nudge dialog box.
     */
    public static DialogBox getNudgeDialog(String text) {
        return getNudgeDialog(text, false);
    }

    /**
     * Creates a dialog aligned to the left for a response from Nudge.
     *
     * @param text response generated by Nudge.
     * @param isError whether the response should use prominent error styling.
     * @return Nudge dialog box.
     */
    public static DialogBox getNudgeDialog(String text, boolean isError) {
        DialogBox dialogBox = new DialogBox(text);
        dialogBox.configureNudgeLayout(isError);
        return dialogBox;
    }

    /**
     * Places the Nudge avatar on the left and applies response-specific styling.
     *
     * @param isError whether the response should use prominent error styling.
     */
    private void configureNudgeLayout(boolean isError) {
        ObservableList<Node> flippedChildren =
                FXCollections.observableArrayList(getChildren());
        Collections.reverse(flippedChildren);
        getChildren().setAll(flippedChildren);
        setAlignment(Pos.TOP_LEFT);
        dialog.getStyleClass().add("reply-label");
        dialog.maxWidthProperty().bind(
                Bindings.max(160, widthProperty().subtract(NUDGE_BUBBLE_SIDE_SPACE)));
        avatar.setImage(NUDGE_AVATAR);
        avatar.setAccessibleText("Nudge");
        setAvatarSize(NUDGE_AVATAR_SIZE);
        if (isError) {
            dialog.getStyleClass().add("error-label");
        }
    }

    private void setAvatarSize(double size) {
        avatar.setFitHeight(size);
        avatar.setFitWidth(size);
    }

    private static Image loadImage(String resourcePath) {
        URL resource = DialogBox.class.getResource(resourcePath);
        if (resource == null) {
            throw new IllegalStateException("Unable to load image: " + resourcePath);
        }
        return new Image(resource.toExternalForm());
    }
}
