package nudge.gui;

import java.io.IOException;
import java.util.Collections;

import javafx.beans.binding.Bindings;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/**
 * Represents one chat message with a text bubble and a speaker badge.
 */
public class DialogBox extends HBox {
    @FXML
    private Label dialog;
    @FXML
    private Label avatar;

    private DialogBox(String text) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(
                    DialogBox.class.getResource("/view/DialogBox.fxml"));
            fxmlLoader.setController(this);
            fxmlLoader.setRoot(this);
            fxmlLoader.load();
        } catch (IOException exception) {
            throw new IllegalStateException("Unable to load a dialog box.", exception);
        }

        dialog.setText(text);
        dialog.maxWidthProperty().bind(Bindings.max(140, widthProperty().subtract(82)));
    }

    /**
     * Creates a dialog aligned to the right for a command entered by the user.
     *
     * @param text command entered by the user.
     * @return user dialog box.
     */
    public static DialogBox getUserDialog(String text) {
        return new DialogBox(text);
    }

    /**
     * Creates a dialog aligned to the left for a response from Nudge.
     *
     * @param text response generated by Nudge.
     * @return Nudge dialog box.
     */
    public static DialogBox getNudgeDialog(String text) {
        DialogBox dialogBox = new DialogBox(text);
        dialogBox.flip();
        return dialogBox;
    }

    /**
     * Places the speaker badge on the left and applies Nudge-specific styling.
     */
    private void flip() {
        ObservableList<Node> flippedChildren =
                FXCollections.observableArrayList(getChildren());
        Collections.reverse(flippedChildren);
        getChildren().setAll(flippedChildren);
        setAlignment(Pos.TOP_LEFT);
        dialog.getStyleClass().add("reply-label");
        avatar.setText("N");
        avatar.getStyleClass().add("nudge-avatar");
    }
}
